import "./globals.css";
import { Inter } from "next/font/google";
import RootStyleRegistry from "./emotion";

import { HeaderMegaMenu } from "@/components/head/header";
import { Afflix } from "@/components/ui/afflix";
import Providers from "@/utils/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PRIMS-platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <RootStyleRegistry>
            <Afflix />
            {children}
          </RootStyleRegistry>
        </Providers>
      </body>
    </html>
  );
}
